import discord
from logging import getLogger
import re
from axyn.database import MessageRecord


_logger = getLogger(__name__)


def is_command(text):
    """Check if the given text appears to be a command."""

    if text.startswith("pls "):
        return True

    return re.match(r"^\w{0,3}[^0-9a-zA-Z\s\'](?=\w)", text) is not None


def is_direct(client, message):
    """Return whether the given message is directly talking to Axyn."""

    return (
        message.channel.type == discord.ChannelType.private
        or client.user.mentioned_in(message)
        or (
            message.reference
            and message.reference.resolved
            and message.reference.resolved.author == client.user
        )
        or "axyn" in message.channel.name
    )


def is_valid(message: MessageRecord) -> bool:
    """
    Return whether the given message is worth processing.

    This excludes messages which have no content stored, or whose content
    is spam.
    """

    if not message.revisions:
        _logger.debug(f"{message.message_id} is not valid because no revisions were saved")
        return False

    for revision in message.revisions:
        if is_command(revision.content):
            _logger.debug(f"{message.message_id} is not valid because a revision looks like a command")
            return False

    return True


def is_valid_response(message: MessageRecord) -> bool:
    """
    Return whether the given message is worth indexing as a response.

    This excludes the same things as ``is_valid``, and also excludes
    messages generated by bots.
    """

    if not message.author.human:
        _logger.debug(f"{message.message_id} is not valid because its author is not human")
        return False

    return is_valid(message)


def is_valid_prompt(current: MessageRecord, prompt: MessageRecord) -> bool:
    """
    Return whether the given message is worth indexing as a prompt for the
    given response.

    This excludes the same things as ``is_valid``, and also excludes cases
    where a user replies to themself.

    This does not do any checks on the response, which is assumed to
    already be valid.
    """

    if prompt.author == current.author:
        _logger.debug(f"{current.message_id} is not valid because {prompt.message_id} has the same author")
        return False

    if prompt.deleted_at is not None:
        # If the prompt was deleted before the response was created, we can't
        # be sure whether they are replying to this or the message before.
        if prompt.deleted_at < current.created_at:
            _logger.debug(f"{current.message_id} is not valid because {prompt.message_id} was deleted prior")
            return False

    return is_valid(prompt)


def reason_not_to_reply(message):
    """If the given message shouldn't be replied to, return a reason why."""

    if (
        message.type != discord.MessageType.default and
        message.type != discord.MessageType.reply
    ):
        return "this is not a regular message"

    if len(message.content) == 0:
        return "this message has no text"

    if message.author.bot or message.author.system:
        return "this message is authored by a bot"

    if (
        message.channel.type != discord.ChannelType.private and
        is_command(message.content)
    ):
        return "this message looks like a bot command"

